### Environment file for the Hull Microbiome Cluster Workflow with fastp, Kraken2, and RGI ###

name: HMCW

channels:
  - conda-forge
  - bioconda

dependencies:
  - snakemake>=6.6.1
  - biopython
  - python>=3.7
  - pandas
  - git
  - wget
  - unzip
  - mamba

# Sequence preprocessing
  - fastp # read QC
  - flye # assembly
  - minimap2 # host removal
  - samtools # host removal
  - metabat2 # binning for MAGs

# Taxonomy assignment
  - kraken2 # taxonomy assignment

# Creating reports and figures
  - seqkit # read statistics throughout workflow
  - biom-format # file format conversion for analysis
  - kraken-biom # creates BIOM file from kraken output

# Packages for analysis in R
  - r-base==3.6.3
  - r-tidyverse
  - r-dplyr
  - r-vegan
  - r-tibble
  - r-rcolorbrewer
  - r-ggplot2
  - r-gdata
  - r-ggrepel
  - r-ggfortify
  - r-stringi
  - r-gplots