### Environment file for the Hull Microbiome Cluster Workflow with fastp, Kraken2, and RGI ###

name: HMCW

channels:
  - conda-forge
  - bioconda

dependencies:
  - snakemake>=6.6.1
  - biopython
  - python>=3.7
  - pandas
  - git
  - wget
  - unzip
  - mamba

# Sequence preprocessing
  - fastp

# Taxonomy assignment
  - kraken2

# Creating reports and figures
  - seqkit
  - biom-format
  - kraken-biom # creates BIOM file from kraken output
